---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dddzzz999/springconfigserver2_config
          #username
          #password
          search-paths:
          - 'station*'